name: build

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        token: ${{ secrets.PAT }}
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Setup project
      run: bash ./scripts/setup.sh
    - name: Use virtual environment
      run: source ./venv/bin/activate
    - name: Build package
      run: |
        source ./venv/bin/activate
        
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        
        bash ./scripts/module.sh
    - name: Build executable
      run: bash ./scripts/build.sh
